# Generated by Django 2.2.1 on 2019-05-23 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=255)),
                ('title_slag', models.SlugField(max_length=255)),
                ('priority', models.IntegerField(choices=[(0, 'High'), (1, 'Medium'), (2, 'Low')])),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_manager_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StateDeliveryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'New'), (1, 'Accepted'), (2, 'Completed'), (3, 'Declined'), (4, 'Cancelled')], default=0)),
                ('state_change_date', models.DateTimeField(auto_now=True)),
                ('delivery_tak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_state', to='delivery_system.DeliveryTask')),
                ('state_change_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_change_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
