# Generated by Django 2.2.1 on 2019-05-23 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_system', '0002_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_list', to=settings.AUTH_USER_MODEL, verbose_name='Staff'),
        ),
    ]
