# Generated by Django 2.2.1 on 2019-05-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_system', '0003_auto_20190523_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverytask',
            name='priority',
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='title_name',
            field=models.CharField(max_length=255, verbose_name='Task Name'),
        ),
    ]
