# Generated by Django 2.2.1 on 2019-05-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_system', '0005_remove_deliverytask_title_slag'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='priority',
            field=models.IntegerField(choices=[(0, 'High'), (1, 'Medium'), (2, 'Low')], default=0),
        ),
    ]
