# Generated by Django 2.2.1 on 2019-05-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_system', '0006_deliverytask_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='title_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Task Name'),
        ),
    ]
