# Generated by Django 2.2.1 on 2019-05-23 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery_system', '0007_auto_20190523_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='title_name',
            field=models.CharField(max_length=255, verbose_name='Task Name'),
        ),
        migrations.AlterUniqueTogether(
            name='deliverytask',
            unique_together={('title_name', 'created_by')},
        ),
    ]
