# Generated by Django 2.2.1 on 2019-05-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_system', '0008_auto_20190523_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='current_state',
            field=models.IntegerField(default=0, verbose_name='Current State'),
        ),
    ]
