# Generated by Django 2.2.1 on 2019-05-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_system', '0009_deliverytask_current_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statedeliverytask',
            options={'ordering': ['state_change_date']},
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
